'use strict';
const ROOM_COLORS = ['#90caf9', '#a5d6a7', '#ffcc80', '#ce93d8', '#80cbc4', '#ef9a9a', '#fff59d', '#b0bec5'];

const DEFAULT_SETTINGS = {
  grid: 25, snap: true, showGrid: true, showDims: true, showArea: true, showRoomNames: true,
  labelSize: 20, wallThickness: 15, wallColor: '', roomOpacity: 0.28, itemShadow: true, symStyle: 'b', viewRot: 0, unit: 'm', wallH3: 250, look3d: 'auto', walls3d: 'auto', all3d: false, theme: 'auto',
  pollSec: 4, rectWalls: true, liveTap: 'toggle',
};

// Farben je Kategorie
const CF = '#d7ccc8', CA = '#cfd8dc', CW = '#b3e5fc', CH = '#ffccbc', CS = '#c5e1a5', CB = '#eceff1';

function T(cat, id, name, icon, w, h, color, o = {}) {
  return { cat, id, name, icon, w, h, color, leaves: o.leaves || 0, shape: o.shape || 'rect', glow: !!o.glow, hint: o.hint || '', wall: !!o.wall };
}

// Maße in cm
const LIB = [
  T('Licht', 'lamp_ceiling', 'Deckenlampe', '💡', 34, 34, CB, { shape: 'ellipse', glow: true, hint: 'light' }),
  T('Licht', 'lamp_floor', 'Stehlampe', '🪔', 30, 30, CB, { shape: 'ellipse', glow: true, hint: 'light' }),
  T('Licht', 'lamp_wall', 'Wandlampe', '🔆', 24, 12, CB, { glow: true, hint: 'light' }),
  T('Licht', 'lamp_spot', 'Spot', '🔦', 16, 16, CB, { shape: 'ellipse', glow: true, hint: 'light' }),
  T('Licht', 'lamp_strip', 'LED-Streifen', '✨', 150, 8, CB, { glow: true, hint: 'light' }),

  T('Möbel', 'bed_double', 'Doppelbett', '🛏️', 180, 200, CF),
  T('Möbel', 'bed_single', 'Einzelbett', '🛏️', 90, 200, CF),
  T('Möbel', 'bed_kid', 'Kinderbett', '🛏️', 70, 140, CF),
  T('Möbel', 'sofa', 'Sofa', '🛋️', 200, 90, CF),
  T('Möbel', 'armchair', 'Sessel', '🛋️', 80, 80, CF),
  T('Möbel', 'table_coffee', 'Couchtisch', '', 100, 60, CF),
  T('Möbel', 'table_dining', 'Esstisch', '🍽️', 160, 90, CF),
  T('Möbel', 'chair', 'Stuhl', '🪑', 45, 45, CF),
  T('Möbel', 'desk', 'Schreibtisch', '🖥️', 140, 70, CF),
  T('Möbel', 'wardrobe', 'Kleiderschrank', '👔', 200, 60, CF),
  T('Möbel', 'shelf', 'Regal', '📚', 100, 35, CF),
  T('Möbel', 'dresser', 'Kommode', '🗄️', 100, 45, CF),
  T('Möbel', 'tv_board', 'TV-Board', '📺', 160, 40, CF),

  T('Küche & Bad', 'fridge', 'Kühlschrank', '🧊', 60, 65, CA),
  T('Küche & Bad', 'stove', 'Herd', '🍳', 60, 60, CA),
  T('Küche & Bad', 'sink_kitchen', 'Spüle', '🚰', 120, 60, CA),
  T('Küche & Bad', 'dishwasher', 'Spülmaschine', '🫧', 60, 60, CA),
  T('Küche & Bad', 'washer', 'Waschmaschine', '🧺', 60, 60, CA),
  T('Küche & Bad', 'bathtub', 'Badewanne', '🛁', 170, 75, CW),
  T('Küche & Bad', 'shower', 'Dusche', '🚿', 90, 90, CW),
  T('Küche & Bad', 'toilet', 'WC', '🚽', 40, 65, CW),
  T('Küche & Bad', 'basin', 'Waschbecken', '🚰', 60, 45, CW),

  T('Heizung & Klima', 'radiator', 'Heizkörper', '♨️', 100, 12, CH, { hint: 'climate' }),
  T('Heizung & Klima', 'thermostat', 'Thermostat', '🌡️', 22, 22, CH, { shape: 'ellipse', hint: 'climate' }),
  T('Heizung & Klima', 'ac', 'Klimagerät', '❄️', 90, 25, CH, { hint: 'climate' }),
  T('Heizung & Klima', 'fan', 'Ventilator', '🌀', 40, 40, CH, { shape: 'ellipse', hint: 'fan' }),
  T('Heizung & Klima', 'fireplace', 'Kamin / Ofen', '🔥', 80, 40, CH),
  T('Heizung & Klima', 'boiler', 'Heizkessel', '🔥', 60, 60, CH),

  T('Smart Home', 'outlet', 'Steckdose', '🔌', 16, 16, CS, { shape: 'ellipse', hint: 'switch' }),
  T('Smart Home', 'switch', 'Schalter', '🎚️', 16, 16, CS, { shape: 'ellipse', hint: 'switch' }),
  T('Smart Home', 'sensor_temp', 'Temperatursensor', '🌡️', 18, 18, CS, { shape: 'ellipse', hint: 'sensor' }),
  T('Smart Home', 'sensor_hum', 'Feuchtesensor', '💧', 18, 18, CS, { shape: 'ellipse', hint: 'sensor' }),
  T('Smart Home', 'sensor_motion', 'Bewegungsmelder', '👁️', 18, 18, CS, { shape: 'ellipse', hint: 'binary_sensor' }),
  T('Smart Home', 'sensor_contact', 'Tür-/Fensterkontakt', '🧲', 16, 16, CS, { shape: 'ellipse', hint: 'binary_sensor' }),
  T('Smart Home', 'smoke', 'Rauchmelder', '🚨', 18, 18, CS, { shape: 'ellipse', hint: 'binary_sensor' }),
  T('Smart Home', 'camera', 'Kamera', '📷', 20, 20, CS, { shape: 'ellipse', hint: 'camera' }),
  T('Smart Home', 'speaker', 'Lautsprecher', '🔊', 24, 24, CS, { hint: 'media_player' }),
  T('Smart Home', 'blind', 'Rollladen / Jalousie', '🪟', 100, 10, CS, { hint: 'cover' }),
  T('Smart Home', 'router', 'Router', '📶', 24, 18, CS),
  T('Smart Home', 'dongle', 'Zigbee-/Matter-Stick', '📡', 20, 20, CS, { shape: 'ellipse' }),
  T('Smart Home', 'vacuum', 'Saugroboter', '🤖', 35, 35, CS, { shape: 'ellipse', hint: 'vacuum' }),
  T('Smart Home', 'bell', 'Klingel', '🔔', 16, 16, CS, { shape: 'ellipse' }),
  T('Smart Home', 'lock', 'Türschloss', '🔒', 16, 16, CS, { shape: 'ellipse', hint: 'lock' }),
  T('Smart Home', 'wallbox', 'Wallbox', '⚡', 30, 20, CS),
  T('Smart Home', 'meter_power', 'Stromzähler', '⚡', 40, 25, CS, { hint: 'sensor' }),
  T('Smart Home', 'meter_gas', 'Gaszähler', '🔥', 30, 25, CS, { hint: 'sensor' }),

  T('Licht', 'lamp_pendant', 'Pendelleuchte', '🏮', 40, 40, CB, { shape: 'ellipse', glow: true, hint: 'light' }),
  T('Licht', 'chandelier', 'Kronleuchter', '🕯️', 60, 60, CB, { shape: 'ellipse', glow: true, hint: 'light' }),
  T('Licht', 'lamp_table', 'Tischlampe', '💡', 22, 22, CB, { shape: 'ellipse', glow: true, hint: 'light' }),
  T('Licht', 'lamp_desk', 'Schreibtischlampe', '💡', 20, 20, CB, { shape: 'ellipse', glow: true, hint: 'light' }),
  T('Licht', 'lamp_night', 'Nachtlicht', '🌙', 12, 12, CB, { shape: 'ellipse', glow: true, hint: 'light' }),
  T('Licht', 'lamp_mirror', 'Spiegelleuchte', '✨', 60, 10, CB, { glow: true, hint: 'light' }),
  T('Licht', 'light_panel', 'LED-Panel', '⬜', 60, 60, CB, { glow: true, hint: 'light' }),
  T('Licht', 'lamp_bulb', 'Smarte Glühbirne', '💡', 10, 10, CB, { shape: 'ellipse', glow: true, hint: 'light' }),
  T('Garten', 'lamp_outdoor', 'Außenleuchte', '🏮', 22, 22, CB, { shape: 'ellipse', glow: true, hint: 'light' }),
  T('Garten', 'lamp_garden', 'Gartenleuchte', '🌿', 15, 15, CB, { shape: 'ellipse', glow: true, hint: 'light' }),
  T('Möbel', 'sofa_corner', 'Ecksofa', '🛋️', 250, 180, CF),
  T('Möbel', 'sofa_2', '2er-Sofa', '🛋️', 150, 90, CF),
  T('Möbel', 'stool', 'Hocker', '🪑', 40, 40, CF, { shape: 'ellipse' }),
  T('Möbel', 'bench', 'Sitzbank', '🪑', 120, 40, CF),
  T('Möbel', 'table_side', 'Beistelltisch', '', 45, 45, CF, { shape: 'ellipse' }),
  T('Möbel', 'table_round', 'Runder Tisch', '🍽️', 110, 110, CF, { shape: 'ellipse' }),
  T('Möbel', 'table_bar', 'Bartisch', '🍸', 140, 60, CF),
  T('Möbel', 'sideboard', 'Sideboard', '🗄️', 180, 45, CF),
  T('Möbel', 'wall_unit', 'Schrankwand', '🗄️', 300, 50, CF),
  T('Möbel', 'bookcase', 'Bücherregal', '📚', 80, 30, CF),
  T('Möbel', 'nightstand', 'Nachttisch', '', 45, 40, CF),
  T('Möbel', 'vanity', 'Frisiertisch', '🪞', 100, 45, CF),
  T('Möbel', 'wardrobe_sliding', 'Schiebetürenschrank', '👔', 250, 65, CF),
  T('Möbel', 'coat_rack', 'Garderobe', '🧥', 100, 30, CF),
  T('Möbel', 'shoe_rack', 'Schuhschrank', '👟', 80, 30, CF),
  T('Möbel', 'bed_bunk', 'Hochbett', '🛏️', 90, 200, CF),
  T('Möbel', 'crib', 'Babybett', '🍼', 60, 120, CF),
  T('Möbel', 'changing', 'Wickelkommode', '🍼', 90, 70, CF),
  T('Möbel', 'highchair', 'Hochstuhl', '🪑', 50, 50, CF),
  T('Möbel', 'desk_corner', 'Eckschreibtisch', '🖥️', 160, 140, CF),
  T('Möbel', 'office_chair', 'Bürostuhl', '🪑', 60, 60, CF, { shape: 'ellipse' }),
  T('Möbel', 'piano', 'Klavier', '🎹', 150, 60, CF),
  T('Möbel', 'mirror', 'Spiegel', '🪞', 60, 5, CF),
  T('Möbel', 'daybed', 'Gästebett / Schlafsofa', '🛏️', 140, 200, CF),
  T('Möbel', 'recliner', 'Relaxsessel', '🛋️', 85, 95, CF),
  T('Möbel', 'ottoman', 'Sitzpuff', '', 50, 50, CF, { shape: 'ellipse' }),
  T('Möbel', 'cabinet', 'Schrank', '🗄️', 90, 45, CF),
  T('Möbel', 'tv_stand', 'TV-Wand / Lowboard', '📺', 200, 45, CF),
  T('Möbel', 'bar_stool', 'Barhocker', '🪑', 38, 38, CF, { shape: 'ellipse' }),
  T('Küche & Bad', 'kitchen_island', 'Kücheninsel', '🍽️', 180, 90, CA),
  T('Küche & Bad', 'counter', 'Arbeitsplatte / Zeile', '', 120, 60, CA),
  T('Küche & Bad', 'cabinet_base', 'Unterschrank', '', 60, 60, CA),
  T('Küche & Bad', 'cabinet_wall', 'Oberschrank', '', 60, 35, CA),
  T('Küche & Bad', 'oven', 'Backofen', '♨️', 60, 60, CA),
  T('Küche & Bad', 'microwave', 'Mikrowelle', '📦', 45, 35, CA),
  T('Küche & Bad', 'hood', 'Dunstabzug', '🌀', 60, 50, CA),
  T('Küche & Bad', 'freezer', 'Gefrierschrank', '🧊', 60, 65, CA),
  T('Küche & Bad', 'fridge_side', 'Side-by-Side-Kühlschrank', '🧊', 90, 70, CA),
  T('Küche & Bad', 'coffee', 'Kaffeemaschine', '☕', 25, 35, CA, { hint: 'switch' }),
  T('Küche & Bad', 'kettle', 'Wasserkocher', '♨️', 20, 20, CA, { hint: 'switch' }),
  T('Küche & Bad', 'dryer', 'Trockner', '🧺', 60, 60, CA),
  T('Küche & Bad', 'dishwasher_tall', 'Geschirrspüler (hoch)', '🫧', 60, 60, CA),
  T('Küche & Bad', 'trash', 'Mülleimer', '🗑️', 35, 35, CA),
  T('Küche & Bad', 'pantry', 'Vorratsschrank', '🥫', 60, 50, CA),
  T('Küche & Bad', 'basin_double', 'Doppelwaschbecken', '🚰', 120, 50, CW),
  T('Küche & Bad', 'bidet', 'Bidet', '🚽', 40, 60, CW),
  T('Küche & Bad', 'mirror_cabinet', 'Spiegelschrank', '🪞', 60, 15, CW),
  T('Küche & Bad', 'towel_radiator', 'Handtuchheizkörper', '♨️', 60, 12, CH, { hint: 'climate' }),
  T('Küche & Bad', 'sauna', 'Sauna', '🧖', 200, 200, CW),
  T('Küche & Bad', 'whirlpool', 'Whirlpool', '🛁', 200, 200, CW, { shape: 'ellipse' }),
  T('Küche & Bad', 'water_heater', 'Boiler / Durchlauferhitzer', '🚿', 40, 40, CW, { hint: 'switch' }),
  T('Küche & Bad', 'utility_sink', 'Ausguss / Waschtrog', '🚰', 60, 50, CW),
  T('Küche & Bad', 'washstand', 'Waschtisch', '🚰', 90, 50, CW),
  T('Küche & Bad', 'shower_tray', 'Duschwanne', '🚿', 90, 90, CW),
  T('Küche & Bad', 'shower_walkin', 'Walk-in-Dusche', '🚿', 120, 90, CW),
  T('Küche & Bad', 'toilet_wall', 'Wand-WC', '🚽', 40, 55, CW),
  T('Heizung & Klima', 'floor_heating', 'Fußbodenheizung', '♨️', 100, 100, CH, { hint: 'climate' }),
  T('Heizung & Klima', 'heat_pump', 'Wärmepumpe', '♨️', 120, 80, CH, { hint: 'climate' }),
  T('Heizung & Klima', 'air_purifier', 'Luftreiniger', '🌬️', 30, 30, CH, { shape: 'ellipse', hint: 'fan' }),
  T('Heizung & Klima', 'humidifier', 'Luftbefeuchter', '💧', 25, 25, CH, { shape: 'ellipse', hint: 'humidifier' }),
  T('Heizung & Klima', 'dehumidifier', 'Luftentfeuchter', '💧', 35, 25, CH, { hint: 'humidifier' }),
  T('Heizung & Klima', 'ventilation', 'Lüftungsgerät', '🌀', 60, 60, CH, { hint: 'fan' }),
  T('Heizung & Klima', 'fan_ceiling', 'Deckenventilator', '🌀', 100, 100, CH, { shape: 'ellipse', hint: 'fan' }),
  T('Heizung & Klima', 'pellet', 'Pelletofen', '🔥', 60, 60, CH),
  T('Heizung & Klima', 'water_tank', 'Pufferspeicher', '🛢️', 80, 80, CH, { shape: 'ellipse' }),
  T('Heizung & Klima', 'heater_elec', 'Heizlüfter / Heizstrahler', '♨️', 30, 25, CH, { hint: 'switch' }),
  T('Heizung & Klima', 'heat_valve', 'Heizkörperventil', '🌡️', 12, 12, CH, { shape: 'ellipse', hint: 'climate' }),
  T('Heizung & Klima', 'heat_dist', 'Heizkreisverteiler', '♨️', 60, 20, CH),
  T('Heizung & Klima', 'split_ac', 'Split-Klimagerät', '❄️', 90, 25, CH, { hint: 'climate' }),
  T('Heizung & Klima', 'solar_thermal', 'Solarthermie-Station', '☀️', 50, 40, CH),
  T('Heizung & Klima', 'chimney_stove', 'Kaminofen', '🔥', 60, 50, CH),
  T('Smart Home', 'plug', 'Zwischenstecker', '🔌', 12, 12, CS, { shape: 'ellipse', hint: 'switch' }),
  T('Smart Home', 'dimmer', 'Dimmer', '🎚️', 14, 14, CS, { shape: 'ellipse', hint: 'light' }),
  T('Smart Home', 'button', 'Taster / Knopf', '🔘', 12, 12, CS, { shape: 'ellipse', hint: 'switch' }),
  T('Smart Home', 'scene_switch', 'Szenentaster', '🔘', 14, 14, CS, { shape: 'ellipse', hint: 'switch' }),
  T('Smart Home', 'remote', 'Fernbedienung', '🎛️', 10, 18, CS),
  T('Smart Home', 'wall_tablet', 'Wand-Tablet / Display', '📱', 25, 16, CS),
  T('Smart Home', 'hub', 'Hub / Gateway', '📡', 15, 15, CS, { shape: 'ellipse' }),
  T('Smart Home', 'sensor_presence', 'Präsenzsensor', '👁️', 14, 14, CS, { shape: 'ellipse', hint: 'binary_sensor' }),
  T('Smart Home', 'sensor_lux', 'Helligkeitssensor', '☀️', 14, 14, CS, { shape: 'ellipse', hint: 'sensor' }),
  T('Smart Home', 'sensor_co2', 'CO₂-/Luftqualitätssensor', '🌫️', 16, 16, CS, { shape: 'ellipse', hint: 'sensor' }),
  T('Smart Home', 'sensor_leak', 'Wassermelder', '💧', 14, 14, CS, { shape: 'ellipse', hint: 'binary_sensor' }),
  T('Smart Home', 'sensor_vibr', 'Vibrationssensor', '〰️', 12, 12, CS, { shape: 'ellipse', hint: 'binary_sensor' }),
  T('Smart Home', 'sensor_co', 'CO-Melder', '🚨', 16, 16, CS, { shape: 'ellipse', hint: 'binary_sensor' }),
  T('Smart Home', 'sensor_gas', 'Gasmelder', '🚨', 16, 16, CS, { shape: 'ellipse', hint: 'binary_sensor' }),
  T('Smart Home', 'glassbreak', 'Glasbruchmelder', '🚨', 14, 14, CS, { shape: 'ellipse', hint: 'binary_sensor' }),
  T('Smart Home', 'siren', 'Sirene', '🚨', 16, 16, CS, { shape: 'ellipse' }),
  T('Smart Home', 'doorbell_cam', 'Video-Türklingel', '🔔', 14, 22, CS, { hint: 'camera' }),
  T('Smart Home', 'camera_ptz', 'Schwenk-Kamera', '📹', 20, 20, CS, { shape: 'ellipse', hint: 'camera' }),
  T('Smart Home', 'garage_opener', 'Garagentorantrieb', '🚪', 30, 20, CS, { hint: 'cover' }),
  T('Smart Home', 'curtain_motor', 'Vorhangmotor', '🪟', 150, 8, CS, { hint: 'cover' }),
  T('Smart Home', 'awning', 'Markise', '⛱️', 300, 25, CS, { hint: 'cover' }),
  T('Smart Home', 'shutter_outdoor', 'Raffstore', '🪟', 120, 10, CS, { hint: 'cover' }),
  T('Smart Home', 'smart_meter', 'Smart Meter', '⚡', 30, 20, CS, { hint: 'sensor' }),
  T('Smart Home', 'inverter', 'Solar-Wechselrichter', '☀️', 40, 25, CS, { hint: 'sensor' }),
  T('Smart Home', 'battery', 'Batteriespeicher', '🔋', 50, 25, CS, { hint: 'sensor' }),
  T('Smart Home', 'heat_meter', 'Wärmemengenzähler', '🌡️', 25, 20, CS, { hint: 'sensor' }),
  T('Smart Home', 'water_meter', 'Wasserzähler', '💧', 25, 20, CS, { hint: 'sensor' }),
  T('Garten', 'weather', 'Wetterstation', '🌦️', 20, 20, CS, { shape: 'ellipse', hint: 'sensor' }),
  T('Garten', 'irrigation', 'Bewässerungsventil', '💧', 16, 16, CS, { shape: 'ellipse', hint: 'valve' }),
  T('Garten', 'pool_pump', 'Poolpumpe', '🌊', 40, 30, CS, { hint: 'switch' }),
  T('Smart Home', 'smart_tv', 'Smart-TV', '📺', 120, 8, CS, { hint: 'media_player' }),
  T('Smart Home', 'soundbar', 'Soundbar', '🔊', 100, 10, CS, { hint: 'media_player' }),
  T('Smart Home', 'smart_speaker', 'Smart Speaker', '🔊', 15, 15, CS, { shape: 'ellipse', hint: 'media_player' }),
  T('Smart Home', 'led_ctrl', 'LED-Controller', '💡', 15, 10, CS, { hint: 'light' }),
  T('Smart Home', 'zigbee_router', 'Zigbee-Router', '📶', 14, 14, CS, { shape: 'ellipse' }),
  T('Smart Home', 'ble_proxy', 'Bluetooth-Proxy', '📶', 14, 14, CS, { shape: 'ellipse' }),
  T('Smart Home', 'esp', 'ESP-/DIY-Gerät', '🧩', 18, 12, CS),
  T('Smart Home', 'alarm_panel', 'Alarmzentrale', '🛡️', 20, 15, CS, { hint: 'alarm_control_panel' }),
  T('Smart Home', 'keypad', 'Codeschloss / Keypad', '🔢', 12, 16, CS),
  T('Smart Home', 'fingerprint', 'Fingerprint-Leser', '☝️', 12, 12, CS, { shape: 'ellipse', hint: 'lock' }),
  T('Smart Home', 'mailbox_sensor', 'Briefkasten-Sensor', '📬', 14, 14, CS, { shape: 'ellipse', hint: 'binary_sensor' }),
  T('Smart Home', 'pet_feeder', 'Futterautomat', '🐾', 25, 25, CS, { shape: 'ellipse', hint: 'switch' }),
  T('Smart Home', 'nas', 'NAS / Server', '🗄️', 20, 30, CS),
  T('Smart Home', 'pc', 'PC / Rechner', '🖥️', 20, 45, CS),
  T('Smart Home', 'ups', 'USV', '🔋', 25, 35, CS, { hint: 'sensor' }),
  T('Smart Home', 'knx', 'KNX-/Aktor-Verteilung', '🧰', 60, 20, CS),
  T('Smart Home', 'ir_blaster', 'IR-Sender', '📡', 12, 12, CS, { shape: 'ellipse' }),
  T('Smart Home', 'smart_valve', 'Wasser-Hauptventil', '🚰', 16, 16, CS, { shape: 'ellipse', hint: 'valve' }),
  T('Garten', 'rain_sensor', 'Regensensor', '🌧️', 14, 14, CS, { shape: 'ellipse', hint: 'binary_sensor' }),
  T('Smart Home', 'wind_sensor', 'Windsensor', '🌬️', 14, 14, CS, { shape: 'ellipse', hint: 'sensor' }),
  T('Smart Home', 'window_handle', 'Fenstergriff-Sensor', '🧲', 12, 12, CS, { shape: 'ellipse', hint: 'binary_sensor' }),
  T('Smart Home', 'radiator_valve', 'Smartes Heizkörperthermostat', '🌡️', 14, 14, CS, { shape: 'ellipse', hint: 'climate' }),
  T('Smart Home', 'smart_blind_ctrl', 'Rollladen-Aktor', '🪟', 16, 16, CS, { shape: 'ellipse', hint: 'cover' }),
  T('Smart Home', 'smart_light_sw', 'Lichtschalter', '💡', 14, 14, CS, { shape: 'ellipse', hint: 'light' }),
  T('Smart Home', 'powerstrip', 'Steckdosenleiste', '🔌', 40, 8, CS, { hint: 'switch' }),
  T('Smart Home', 'thread', 'Thread-Border-Router', '📶', 16, 16, CS, { shape: 'ellipse' }),
  T('Smart Home', 'ev_charger', 'Ladepunkt E-Auto', '🔌', 25, 20, CS, { hint: 'switch' }),
  T('Büro & Medien', 'monitor', 'Monitor', '🖥️', 60, 20, CB),
  T('Büro & Medien', 'printer', 'Drucker', '🖨️', 40, 35, CB),
  T('Büro & Medien', 'printer3d', '3D-Drucker', '🧱', 40, 40, CB),
  T('Büro & Medien', 'server_rack', 'Serverschrank', '🗄️', 60, 80, CB),
  T('Büro & Medien', 'console', 'Spielkonsole', '🎮', 30, 22, CB),
  T('Büro & Medien', 'projector', 'Beamer', '📽️', 30, 25, CB),
  T('Büro & Medien', 'hifi', 'HiFi-Anlage', '🎶', 45, 35, CB),
  T('Büro & Medien', 'aquarium', 'Aquarium', '🐠', 100, 40, CB),
  T('Büro & Medien', 'workbench', 'Werkbank', '🛠️', 150, 60, CB),
  T('Büro & Medien', 'tool_cabinet', 'Werkzeugschrank', '🧰', 60, 50, CB),
  T('Büro & Medien', 'whiteboard', 'Whiteboard / Pinnwand', '📋', 120, 5, CB),
  T('Garten', 'tree_fruit', 'Obstbaum', '🍎', 200, 200, '#a5d6a7', { shape: 'ellipse' }),
  T('Garten', 'tree_conifer', 'Nadelbaum', '🌲', 160, 160, '#81c784', { shape: 'ellipse' }),
  T('Garten', 'palm', 'Palme', '🌴', 150, 150, '#a5d6a7', { shape: 'ellipse' }),
  T('Garten', 'bush_flower', 'Blühstrauch', '🌸', 90, 90, '#f8bbd0', { shape: 'ellipse' }),
  T('Garten', 'planter', 'Pflanzkübel', '🪴', 50, 50, '#bcaaa4', { shape: 'ellipse' }),
  T('Garten', 'raised_bed', 'Hochbeet', '🥬', 120, 80, '#c5e1a5'),
  T('Garten', 'veggie_patch', 'Gemüsebeet', '🥕', 200, 100, '#a1887f'),
  T('Garten', 'meadow', 'Blumenwiese', '🌼', 300, 200, '#dce775'),
  T('Garten', 'rocks', 'Steine / Findlinge', '🪨', 100, 80, '#cfd8dc', { shape: 'ellipse' }),
  T('Garten', 'hedge_corner', 'Hecke (kurz)', '🌿', 120, 50, '#a5d6a7'),
  T('Garten', 'trellis', 'Rankgitter', '🌱', 100, 6, '#bcaaa4'),
  T('Garten', 'vineyard', 'Spalierobst', '🍇', 300, 20, '#c5e1a5'),
  T('Garten', 'pond', 'Gartenteich', '🪷', 250, 180, '#81d4fa', { shape: 'ellipse' }),
  T('Garten', 'fountain', 'Springbrunnen', '⛲', 80, 80, '#b3e5fc', { shape: 'ellipse' }),
  T('Garten', 'birdbath', 'Vogeltränke', '🐦', 40, 40, '#cfd8dc', { shape: 'ellipse' }),
  T('Garten', 'water_tap', 'Außenwasserhahn', '🚰', 14, 14, '#b0bec5', { shape: 'ellipse' }),
  T('Garten', 'hose_reel', 'Schlauchtrommel', '🪢', 40, 30, '#80cbc4'),
  T('Garten', 'cistern', 'Zisterne / Regenspeicher', '💧', 120, 120, '#90a4ae', { shape: 'ellipse' }),
  T('Garten', 'well', 'Brunnen', '🪣', 90, 90, '#bcaaa4', { shape: 'ellipse' }),
  T('Garten', 'stream', 'Bachlauf', '〰️', 300, 60, '#81d4fa'),
  T('Garten', 'greenhouse', 'Gewächshaus', '🪟', 250, 350, '#e0f2f1'),
  T('Garten', 'pergola', 'Pergola', '🏛️', 300, 400, '#d7ccc8'),
  T('Garten', 'gazebo', 'Pavillon', '⛺', 300, 300, '#d7ccc8', { shape: 'ellipse' }),
  T('Garten', 'woodshed', 'Holzlager', '🪵', 200, 80, '#d7ccc8'),
  T('Garten', 'compost', 'Komposter', '♻️', 100, 100, '#a1887f'),
  T('Garten', 'bin_shelter', 'Mülltonnenbox', '🗑️', 200, 80, '#b0bec5'),
  T('Garten', 'playhouse', 'Spielhaus', '🏠', 150, 150, '#ffe0b2'),
  T('Garten', 'chicken_coop', 'Hühnerstall', '🐔', 150, 100, '#ffe0b2'),
  T('Garten', 'rabbit_hutch', 'Kaninchenstall', '🐇', 120, 60, '#ffe0b2'),
  T('Garten', 'doghouse', 'Hundehütte', '🐕', 70, 90, '#ffe0b2'),
  T('Garten', 'hammock', 'Hängematte', '🛌', 100, 250, '#fff59d'),
  T('Garten', 'bench_garden', 'Gartenbank', '🪑', 150, 55, '#d7ccc8'),
  T('Garten', 'chair_garden', 'Gartenstuhl', '💺', 55, 55, '#d7ccc8'),
  T('Garten', 'swing_seat', 'Hollywoodschaukel', '🛋️', 200, 120, '#fff59d'),
  T('Garten', 'slide', 'Rutsche', '🛝', 80, 250, '#ffcc80'),
  T('Garten', 'birdhouse', 'Vogelhaus', '🏡', 25, 25, '#ffe0b2', { shape: 'ellipse' }),
  T('Garten', 'bee_hotel', 'Insektenhotel', '🐝', 30, 12, '#ffe0b2'),
  T('Garten', 'statue', 'Gartenfigur', '🗿', 30, 30, '#cfd8dc', { shape: 'ellipse' }),
  T('Garten', 'outdoor_kitchen', 'Außenküche', '🍳', 200, 70, '#cfd8dc'),
  T('Garten', 'pizza_oven', 'Pizzaofen', '🍕', 80, 80, '#d7ccc8'),
  T('Garten', 'wood_pile', 'Holzstapel', '🪵', 200, 60, '#d7ccc8'),
  T('Garten', 'wheelbarrow', 'Schubkarre', '🛒', 60, 130, '#cfd8dc'),
  T('Garten', 'solar_panel', 'Solarpanel', '☀️', 170, 100, '#90a4ae'),
  T('Garten', 'privacy_screen', 'Sichtschutz', '🧱', 180, 8, '#d7ccc8'),
  T('Garten', 'garden_gate', 'Gartentür', '🚪', 100, 8, '#bcaaa4'),
  T('Garten', 'stone_wall', 'Mauer / Trockenmauer', '🧱', 300, 30, '#bdbdbd'),
  T('Garten', 'edging', 'Rasenkante / Beetrand', '➖', 300, 6, '#9e9e9e'),
  T('Garten', 'path_stone', 'Gartenweg (Platten)', '🟫', 100, 300, '#d7ccc8'),
  T('Garten', 'path_gravel', 'Kiesweg', '▫️', 100, 300, '#e0e0e0'),
  T('Garten', 'stepping_stones', 'Trittsteine', '👣', 100, 220, '#bdbdbd'),
  T('Garten', 'gravel_area', 'Kiesfläche', '▫️', 300, 200, '#eeeeee'),
  T('Garten', 'patio', 'Pflasterfläche', '🟫', 400, 300, '#cfd8dc'),
  T('Garten', 'deck', 'Holzdeck', '🟫', 400, 300, '#d7b98e'),
  T('Garten', 'lamp_solar', 'Solarleuchte', '🔆', 14, 14, '#fff9c4', { shape: 'ellipse', glow: true, hint: 'light' }),
  T('Garten', 'lamp_post', 'Mastleuchte', '💡', 24, 24, '#fff9c4', { shape: 'ellipse', glow: true, hint: 'light' }),
  T('Garten', 'lamp_spike', 'Erdspieß-Strahler', '🔦', 14, 14, '#fff9c4', { shape: 'ellipse', glow: true, hint: 'light' }),
  T('Garten', 'lamp_flood', 'Fluter / Strahler', '🔦', 25, 15, '#fff9c4', { glow: true, hint: 'light' }),
  T('Garten', 'mower_robot', 'Mähroboter', '🤖', 60, 45, '#a5d6a7'),
  T('Garten', 'mower_station', 'Mäh-Ladestation', '🔌', 40, 30, '#a5d6a7'),
  T('Garten', 'sensor_soil', 'Bodenfeuchtesensor', '🌱', 12, 12, '#c5e1a5', { shape: 'ellipse' }),
  T('Garten', 'sprinkler', 'Rasensprenger', '💦', 16, 16, '#80deea', { shape: 'ellipse' }),
  T('Garten', 'valve_box', 'Ventilbox Bewässerung', '🚿', 40, 30, '#80cbc4'),
  T('Garten', 'pool_robot', 'Poolroboter', '🤖', 50, 40, '#80deea'),
  T('Garten', 'pool_heater', 'Pool-Wärmepumpe', '♨️', 50, 40, '#cfd8dc'),
  T('Garten', 'gate_motor', 'Torantrieb', '⚙️', 30, 20, '#b0bec5'),
  T('Garten', 'cam_garden', 'Garten-Kamera', '📷', 20, 20, '#cfd8dc', { shape: 'ellipse' }),
  T('Garten', 'garden_speaker', 'Garten-Lautsprecher', '🔊', 25, 25, '#b0bec5', { shape: 'ellipse' }),
  T('Garten', 'sensor_garden_motion', 'Außen-Bewegungsmelder', '🚶', 16, 16, '#cfd8dc', { shape: 'ellipse' }),
  T('Außen & Garage', 'car', 'Auto', '🚗', 180, 450, '#cfd8dc'),
  T('Außen & Garage', 'carport', 'Stellplatz / Carport', '🅿️', 280, 520, '#eceff1'),
  T('Außen & Garage', 'garage_door', 'Garagentor', '🚪', 250, 15, CB, { shape: 'door', wall: true }),
  T('Außen & Garage', 'bike', 'Fahrrad / Ständer', '🚲', 60, 180, CB),
  T('Garten', 'terrace_table', 'Gartentisch', '🍽️', 150, 90, CF),
  T('Garten', 'lounger', 'Sonnenliege', '🏖️', 70, 190, CF),
  T('Garten', 'grill', 'Grill', '🍖', 60, 45, CA),
  T('Garten', 'pool', 'Pool', '🏊', 300, 600, '#b3e5fc'),
  T('Garten', 'hot_tub', 'Außen-Whirlpool', '♨️', 200, 200, '#b3e5fc', { shape: 'ellipse' }),
  T('Garten', 'tree', 'Baum', '🌳', 150, 150, '#a5d6a7', { shape: 'ellipse' }),
  T('Garten', 'bush', 'Busch', '🌿', 80, 80, '#c8e6c9', { shape: 'ellipse' }),
  T('Garten', 'hedge', 'Hecke', '🌿', 300, 50, '#a5d6a7'),
  T('Garten', 'fence', 'Zaun', '', 300, 6, '#8d6e63'),
  T('Garten', 'flowerbed', 'Beet', '🌷', 200, 80, '#c5e1a5'),
  T('Garten', 'lawn', 'Rasenfläche', '', 400, 300, '#c8e6c9'),
  T('Garten', 'mailbox', 'Briefkasten', '📬', 30, 20, CB),
  T('Garten', 'gate', 'Gartentor', '🚪', 120, 10, CB),
  T('Garten', 'shed', 'Gartenhaus', '🏠', 250, 200, CF),
  T('Garten', 'trash_bin', 'Mülltonne', '🗑️', 60, 70, '#b0bec5'),
  T('Garten', 'rain_barrel', 'Regentonne', '🛢️', 60, 60, '#b0bec5', { shape: 'ellipse' }),
  T('Garten', 'sandbox', 'Sandkasten', '🏖️', 120, 120, '#ffe0b2'),
  T('Garten', 'trampoline', 'Trampolin', '🤸', 300, 300, '#cfd8dc', { shape: 'ellipse' }),
  T('Garten', 'swing', 'Schaukel', '🛝', 200, 150, CF),
  T('Garten', 'terrace', 'Terrasse / Platten', '', 400, 300, '#d7ccc8'),
  T('Außen & Garage', 'driveway', 'Einfahrt', '', 300, 600, '#cfd8dc'),
  T('Garten', 'firepit', 'Feuerstelle', '🔥', 90, 90, '#ffccbc', { shape: 'ellipse' }),
  T('Garten', 'parasol', 'Sonnenschirm', '⛱️', 200, 200, '#ffe0b2', { shape: 'ellipse' }),
  T('Kinder & Haustiere', 'playmat', 'Spielteppich', '🧸', 150, 150, '#ffe0b2'),
  T('Kinder & Haustiere', 'toy_box', 'Spielzeugkiste', '🧸', 60, 40, CF),
  T('Kinder & Haustiere', 'kid_table', 'Kindertisch', '', 60, 60, CF),
  T('Kinder & Haustiere', 'cat_tree', 'Kratzbaum', '🐈', 60, 60, CF, { shape: 'ellipse' }),
  T('Kinder & Haustiere', 'dog_bed', 'Hundebett', '🐕', 80, 60, '#d7ccc8', { shape: 'ellipse' }),
  T('Kinder & Haustiere', 'litter', 'Katzenklo', '🐈', 40, 50, CB),
  T('Kinder & Haustiere', 'pet_flap', 'Katzenklappe', '🐾', 20, 10, CB),
  T('Kinder & Haustiere', 'cage', 'Käfig / Terrarium', '🐹', 80, 40, CB),
  T('Kinder & Haustiere', 'playpen', 'Laufstall', '🍼', 100, 100, '#ffe0b2'),
  T('Bau & Deko', 'door_sliding', 'Schiebetür', '', 100, 12, CB, { shape: 'door', wall: true }),
  T('Bau & Deko', 'door_front', 'Haustür', '', 100, 15, CB, { shape: 'door', wall: true }),
  T('Bau & Deko', 'door_terrace', 'Terrassentür', '', 180, 15, CB, { shape: 'door', wall: true }),
  T('Bau & Deko', 'window_skylight', 'Dachfenster', '', 80, 15, CB, { shape: 'window', wall: true }),
  T('Bau & Deko', 'window_small', 'Fenster klein', '', 60, 15, CB, { shape: 'window', wall: true }),
  T('Bau & Deko', 'window_corner', 'Fensterband', '', 300, 15, CB, { shape: 'window', wall: true }),
  T('Bau & Deko', 'archway', 'Durchgang', '', 100, 15, CB, { wall: true }),
  T('Bau & Deko', 'stairs_spiral', 'Wendeltreppe', '🪜', 150, 150, CB, { shape: 'ellipse' }),
  T('Bau & Deko', 'elevator', 'Aufzug', '🛗', 110, 140, CB),
  T('Bau & Deko', 'chimney', 'Schornstein', '', 40, 40, '#b0bec5'),
  T('Bau & Deko', 'pillar_round', 'Säule rund', '', 30, 30, '#b0bec5', { shape: 'ellipse' }),
  T('Bau & Deko', 'curtain', 'Vorhang', '', 150, 8, '#e1bee7'),
  T('Bau & Deko', 'painting', 'Bild / Gemälde', '🖼️', 80, 4, CB),
  T('Bau & Deko', 'rug_round', 'Teppich rund', '', 160, 160, '#e1bee7', { shape: 'ellipse' }),
  T('Bau & Deko', 'plant_big', 'Große Pflanze', '🪴', 60, 60, '#c8e6c9', { shape: 'ellipse' }),
  T('Bau & Deko', 'plant_small', 'Kleine Pflanze', '🌱', 25, 25, '#c8e6c9', { shape: 'ellipse' }),
  T('Bau & Deko', 'niche', 'Nische / Vorsprung', '', 80, 30, '#cfd8dc'),
  T('Bau & Deko', 'safe', 'Tresor', '🔐', 40, 40, '#b0bec5'),
  T('Bau & Deko', 'fire_ext', 'Feuerlöscher', '🧯', 15, 15, '#ffccbc', { shape: 'ellipse' }),
  T('Bau & Deko', 'electric_panel', 'Sicherungskasten', '⚡', 40, 15, CS),
  T('Bau & Deko', 'cable_duct', 'Kabelschacht', '', 20, 20, '#b0bec5'),

  T('Garten', 'lamp_arc', 'Bogenleuchte', '🪔', 40, 40, CB, { shape: 'ellipse', glow: true, hint: 'light' }),
  T('Garten', 'light_string', 'Lichterkette', '✨', 200, 6, CB, { glow: true, hint: 'light' }),
  T('Smart Home', 'outlet_double', 'Doppelsteckdose', '🔌', 28, 14, CS, { hint: 'switch' }),
  T('Smart Home', 'outlet_usb', 'USB-Steckdose', '🔌', 16, 16, CS, { shape: 'ellipse', hint: 'switch' }),
  T('Garten', 'outlet_outdoor', 'Außensteckdose', '🔌', 16, 16, CS, { shape: 'ellipse', hint: 'switch' }),
  T('Smart Home', 'outlet_floor', 'Bodensteckdose', '🔌', 16, 16, CS, { shape: 'ellipse', hint: 'switch' }),
  T('Smart Home', 'outlet_smart', 'Smarte Steckdose', '🔌', 16, 16, CS, { shape: 'ellipse', hint: 'switch' }),
  T('Smart Home', 'outlet_cee', 'Herd-/Starkstromanschluss', '⚡', 18, 18, CS, { shape: 'ellipse' }),
  T('Smart Home', 'switch_double', 'Doppelschalter', '🎚️', 16, 16, CS, { hint: 'switch' }),
  T('Smart Home', 'lan_socket', 'LAN-Dose', '🌐', 14, 14, CS),
  T('Smart Home', 'tv_socket', 'Antennen-/TV-Dose', '📺', 14, 14, CS),
  T('Bau & Deko', 'door', 'Tür', '', 90, 15, CB, { shape: 'door', wall: true }),
  T('Bau & Deko', 'door_double', 'Doppeltür', '', 160, 15, CB, { shape: 'door', wall: true }),
  T('Bau & Deko', 'window', 'Fenster (einflügelig)', '', 100, 15, CB, { shape: 'window', wall: true }),
  T('Bau & Deko', 'window_double', 'Fenster doppelflügelig', '', 140, 15, CB, { shape: 'window', wall: true, leaves: 2 }),
  T('Bau & Deko', 'window_double_big', 'Fenster doppelflügelig groß', '', 200, 15, CB, { shape: 'window', wall: true, leaves: 2 }),
  T('Bau & Deko', 'window_big', 'Fenster groß (einflügelig)', '', 200, 15, CB, { shape: 'window', wall: true }),
  T('Bau & Deko', 'stairs', 'Treppe gerade', '🪜', 100, 260, CB),
  T('Bau & Deko', 'stairs_wide', 'Treppe gerade breit', '🪜', 130, 300, CB),
  T('Bau & Deko', 'stairs_L', 'Treppe L-förmig (Viertelwendel)', '🪜', 200, 200, CB),
  T('Bau & Deko', 'stairs_U', 'Treppe U-förmig (Halbwendel)', '🪜', 200, 280, CB),
  T('Bau & Deko', 'stairs_spiral_small', 'Wendeltreppe klein', '🪜', 120, 120, CB, { shape: 'ellipse' }),
  T('Bau & Deko', 'stairs_outdoor', 'Außentreppe', '🪜', 120, 200, '#d7ccc8'),
  T('Bau & Deko', 'stairs_basement', 'Kellertreppe', '🪜', 90, 260, CB),
  T('Bau & Deko', 'plant', 'Pflanze', '🪴', 40, 40, '#c8e6c9', { shape: 'ellipse' }),
  T('Bau & Deko', 'rug', 'Teppich', '', 200, 140, '#e1bee7'),
  T('Bau & Deko', 'pillar', 'Säule', '', 30, 30, '#b0bec5'),
  T('Bau & Deko', 'text', 'Beschriftung', 'Aa', 200, 40, '', { shape: 'text' }),
];

function typeList() {
  const m = new Map();
  LIB.forEach(t => m.set(t.id, { ...t }));
  ((typeof plan !== 'undefined' && plan && plan.customTypes) || []).forEach(t =>
    m.set(t.id, { ...t, custom: true, builtin: LIB.some(b => b.id === t.id) }));
  return [...m.values()];
}
function typeById(id) { return typeList().find(t => t.id === id); }

function newItemFromType(t, x, y) {
  const it = {
    id: uid(), type: t.id, x, y, w: t.w, h: t.h, rot: 0, shape: t.shape || 'rect',
    icon: t.icon || '', image: t.image || '', imgMode: t.imgMode || 'contain', color: t.color || '', label: '', showLabel: true, entity: '',
    showValue: false, glow: !!t.glow, onColor: '', tap: 'auto', svc: '', svcData: '',
    flipX: false, flipY: false, leaves: t.leaves || 1, iconScale: 1, hint: t.hint || '',
  };
  if (it.shape === 'text') { it.label = 'Text'; it.fs = 28; it.color = ''; fitText(it); }
  return it;
}

function fitText(it) {
  const lines = String(it.label || ' ').split('\n');
  const fs = it.fs || 28;
  it.w = Math.max(20, Math.max(...lines.map(l => l.length)) * fs * 0.6 + fs * 0.6);
  it.h = Math.max(fs, lines.length * fs * 1.2 + fs * 0.2);
}
